name: Generate metrics

on:
  workflow_dispatch:        # manual run button
  push:                     # run on updates to README or the workflow
    branches: [ main ]
    paths:
      - '.github/workflows/metrics.yml'
      - 'README.md'
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ParthSharma272
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_output: metrics.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
